name: ai_powered_vpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+2

environment:
  sdk: ">=3.0.5 <4.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.5
  flutter_screenutil: ^5.8.4
  flutter_svg:
  pin_code_fields: ^8.0.1
  font_awesome_flutter: ^10.5.0
  flutter_rating_bar: ^4.0.1
  country_code_picker: ^3.0.0
  get_storage: ^2.1.1
  image_picker: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_core_dart: ^1.0.1
  google_fonts: ^5.1.0
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^4.0.2
  logger: ^1.1.0
  csv: ^5.0.2
  google_mobile_ads: ^3.0.0
  flutter_inappwebview: ^5.7.2+3



dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  flutter_app_name: ^0.1.0
#
flutter_app_name:
  name: "AI Powered VPN"

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/flags/
    - assets/images/auth/
    - assets/images/connection_report/
    - assets/images/dashboard/
    - assets/images/drawer/
    - assets/images/flag/
    - assets/images/screen/
    - assets/images/splash/
    - assets/images/upgrade/
    - assets/images/vpn_connect/
    - assets/images/vpn_location/
    - assets/images/welcome/
    - assets/logo/
    - assets/onboards/
    - assets/vpn/